import "./globals.css";

import type { Metadata } from "next";

import useColorMode from "./useColorMode";
import useFonts from "./useFonts";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "1998 SHOTS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useColorMode();
  const fonts = useFonts();

  return (
    <html lang="en">
      <body className={fonts.className}>
        {/* <Header /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
