import "./globals.css";

import type { Metadata } from "next";

import BodyWrapper from "@/components/BodyWrapper";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ScrollTop from "@/components/ScrollTop";
import { ThemeScope } from "@/context/ThemeScope";

export const metadata: Metadata = {
  title: "1998 SHOTS",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <ThemeScope>
      <BodyWrapper>
        <Header />
        <main>{children}</main>
        <Footer />
        <ScrollTop />
      </BodyWrapper>
    </ThemeScope>
  </html>
);

export default RootLayout;
