import "./globals.css";

import type { Metadata } from "next";

import useFonts from "./useFonts";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ThemeScope } from "@/ThemeContext";

export const metadata: Metadata = {
  title: "1998 SHOTS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fonts = useFonts();

  return (
    <ThemeScope>
      <html lang="en">
        <body className={fonts.className}>
          <Header />
          <main>{children}</main>
          <Footer className="pb-10 pt-5" />
        </body>
      </html>
    </ThemeScope>
  );
}
